# -*- coding: utf-8 -*-
"""Inference_1B

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/19RbeqMcQwazIlcg5uFcOTSSfoxn5F3vm
"""

import streamlit as st
import numpy as np
import pandas as pd
import pickle

# with open('best_model.pkl', 'rb') as file:
#     model = pickle.load(file)

# i move it on the def main

st.markdown("""
    <style>
        body {
            background-color: #fdfdfd; /* Soft white background */
            color: #2f2f2f; /* Neutral dark text */
            font-family: 'Georgia', serif; /* Elegant serif font */
        }

        .stApp {
            background-color: #fdfdfd;
        }

        .stTitle {
            color: #006644; /* Deep emerald for title */
            font-size: 36px;
            font-weight: bold;
            text-align: center;
            margin-top: 20px;
        }

        .stHeader {
            color: #2f2f2f;
            font-size: 24px;
            font-weight: bold;
        }

        .stButton>button {
            background-color: #2ecc71; /* Emerald green */
            color: white;
            font-size: 18px;
            padding: 12px 20px;
            border-radius: 10px;
            border: none;
            font-weight: bold;
            box-shadow: 0 4px 10px rgba(46, 204, 113, 0.3);
            transition: 0.3s;
        }

        .stButton>button:hover {
            background-color: #27ae60; /* Slightly darker emerald */
        }

        .stSelectbox, .stNumberInput, .stSlider {
            background-color: #f5fef8;
            border-radius: 10px;
            border: 1px solid #cce5d0;
            padding: 8px;
            font-size: 16px;
        }

        .stSelectbox>div, .stNumberInput>div {
            font-weight: 600;
            color: #2f2f2f;
        }

        .stSidebar {
            background-color: #e9f9f1; /* light emerald tone */
            border-radius: 12px;
            padding: 20px;
            box-shadow: 0 4px 12px rgba(0, 128, 64, 0.1);
        }

        .stSlider .st-bb {
            font-size: 15px;
            font-weight: 600;
            color: #1c684e;
        }

        h3, .stSubheader {
            color: #006644;
        }

        .stMarkdown, .stWrite {
            font-size: 17px;
            line-height: 1.6;
            color: #2f2f2f;
        }

        .emoji {
            font-size: 26px;
            margin-right: 10px;
        }

        /* Smooth transitions for interactivity */
        .stButton>button, .stSelectbox, .stNumberInput {
            transition: all 0.3s ease-in-out;
        }
    </style>
""", unsafe_allow_html=True)

def main():
    st.title("🏨 Hotel Booking Cancellation Prediction 🏨")
    st.write("""
      Welcome to **INN Hotels**' Booking Analyzer! ✨

      Hotel managers, enhance your booking strategy with this tool that predicts whether a booking will be canceled based on guest details.

      Fill in the reservation information below, and let’s forecast your booking’s status to optimize room occupancy and improve guest experience! 📊💡
      """)

    st.subheader("⏳ Stay Duration")
    no_of_weekend_nights = st.slider("Weekend Nights", min_value = 0, max_value = 7, value = 1)
    no_of_week_nights = st.slider("Week Nights", min_value = 1, max_value = 20, value = 2)

    # layout grid for input data (so there are 2 column shown)
    col1, col2 = st.columns(2)

    with col1:
        st.subheader("🧑‍🤝‍🧑 Guest Information")
        no_of_adults = st.slider("Number of Adults", min_value = 0, max_value = 10, value = 2)
        no_of_children = st.slider("Number of Children", min_value = 0, max_value = 10, value = 0)
        repeated_guest_display = st.selectbox("Returning Guest?", ["Yes", "No"])
        no_of_special_requests = st.slider("Special Requests", min_value = 0, max_value = 5, value = 0)

    with col2:
        st.subheader("💸 Financial Details")
        market_segment_type = st.selectbox("💼 Tipe Market", ['Offline', 'Online', 'Corporate', 'Aviation', 'Complementary'])
        avg_price_per_room = st.number_input("💶 Average Price per Room (€)", min_value = 0.0, max_value = 500.0, value = 100.0, step = 5.00)
        no_of_previous_cancellations = st.slider("Previous Cancellations", min_value = 0, max_value = 10, value = 0)
        no_of_previous_bookings_not_canceled = st.slider("Previous Non-Canceled Bookings", min_value = 0, max_value = 10, value = 1

    st.subheader("🛏️ Booking Details")
    lead_time = st.number_input("⏳ Lead Time (Days before arrival)", min_value = 0, max_value = 365, value = 10)
    arrival_year = st.selectbox("Arrival Year", [2017, 2018])
    arrival_month = st.slider("Arrival Month", min_value = 1, max_value = 12, value = 1)
    arrival_date = st.slider("Arrival Date", min_value = 1, max_value = 31, value = 1)
    room_type_reserved = st.selectbox("Room Type", ['Room_Type 1', 'Room_Type 2', 'Room_Type 3', 'Room_Type 4', 'Room_Type 5', 'Room_Type 6', 'Room_Type 7'])
    type_of_meal_plan = st.selectbox("Meal Plan", ['Meal Plan 1', 'Meal Plan 2', 'Meal Plan 3', 'Not Selected'])
    required_car_parking_space_display = st.selectbox("Car Parking Space Needed?", ["No", "Yes"])

    required_car_parking_space = 1 if required_car_parking_space_display == "Yes" else 0
    repeated_guest = 1 if repeated_guest_display == "Yes" else 0

    # manual One-hot encoding for categorical variables
    # meal plan
    meal_plan_columns = ['Meal Plan 1', 'Meal Plan 2', 'Meal Plan 3', 'Not Selected']
    meal_plan = [1 if type_of_meal_plan == mp else 0 for mp in meal_plan_columns]
    # room type reserved
    room_type_columns = ['Room_Type 1', 'Room_Type 2', 'Room_Type 3', 'Room_Type 4', 'Room_Type 5', 'Room_Type 6', 'Room_Type 7']
    room_type = [1 if room_type_reserved == rt else 0 for rt in room_type_columns]
    # market segment type
    market_segment_columns = ['Offline', 'Online', 'Corporate', 'Aviation', 'Complementary']
    market_segment = [1 if market_segment_type == ms else 0 for ms in market_segment_columns]


    input_data = {
    'no_of_adults': no_of_adults,
    'no_of_children': no_of_children,
    'no_of_weekend_nights': no_of_weekend_nights,
    'no_of_week_nights': no_of_week_nights,
    'required_car_parking_space': required_car_parking_space,
    'lead_time': lead_time,
    'arrival_year': 0 if arrival_year == 2017 else 1,
    'avg_price_per_room': avg_price_per_room,
    'no_of_previous_cancellations': no_of_previous_cancellations,
    'no_of_previous_bookings_not_canceled': no_of_previous_bookings_not_canceled,
    'no_of_special_requests': no_of_special_requests,
    }

    # combine onehot to input_data
    input_data.update(dict(zip(meal_plan_columns, meal_plan)))
    input_data.update(dict(zip(room_type_columns, room_type)))
    input_data.update(dict(zip(market_segment_columns, market_segment)))

    # convert to dataframe
    input_df = pd.DataFrame([input_data])

    # load the trained model (pickled)
    with open('best_model.pkl', 'rb') as file:
        model = pickle.load(file)

    # prediction button
    if st.button("Predict Booking Status"):
        prediction = model.predict(input_df)[0]
        probability = model.predict_proba(input_df)[0][1]  # Probability of cancellation (class 1)

        if prediction == 1:
            st.error(f"❌ Booking is likely to be canceled with a probability of {probability:.2%}.")
        else:
            st.success(f"✅ Booking is likely to be confirmed (Not Canceled) with a probability of {(1 - probability):.2%}.")

if __name__ == '__main__':
    main()

# !npm install localtunnel

# ! stramlit run /content/inference_1b.py &> /content/logs.txt &

# !curl ipv4.icanhazip.com

# !npx localtunnel -- port 8501

