# -*- coding: utf-8 -*-
"""OOP_1B.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1NjQhT2Dq7Yiv9XTvYsXfHC8Z-0GKIyhq

### OOP in Machine Learning

**Machine Learning (ML)** and **Object-Oriented Programming (OOP)** are different but can work well together.

- **ML** focuses on building models that can learn from data and make predictions or decisions.
- **OOP** organizes code into small, reusable pieces called "objects," making it easier to manage and update.

### What are the differences?:
- **ML** is about learning patterns from data.
- **OOP** is about structuring code in a clear, organized way.
  
### Why combine OOP with ML?
- **OOP** helps break the ML process into manageable parts (like data cleaning, training, and testing) by using classes and objects.
- It makes your code **easier to reuse**, **maintain**, and **extend** for different projects.

In the this project, we’ll see how to use OOP to structure ML code in a clean and efficient way :)))
"""

import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split, GridSearchCV
from sklearn.preprocessing import OneHotEncoder, LabelEncoder, RobustScaler
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score, f1_score, roc_auc_score, classification_report

"""**In a nutshell:**
* Class: A template to create objects. It defines what the objects will have (like attributes) and what they can do (like actions).
* Def: A way to create a function inside a class. It tells the object what to do when the function is called.
"""

class DataLoader:
    def __init__(self, filepath):
        self.filepath = filepath
        self.df = None

    def load_data(self):
        self.df = pd.read_csv(self.filepath)
        return self.df

    def clean_data(self):
        df = self.df.copy()
        df['required_car_parking_space'].fillna(df['required_car_parking_space'].median(), inplace=True)
        df['required_car_parking_space'] = df['required_car_parking_space'].astype(int)
        df['avg_price_per_room'].fillna(df['avg_price_per_room'].median(), inplace=True)
        df['type_of_meal_plan'].fillna('Meal Plan 1', inplace=True)
        df.drop('Booking_ID', axis=1, inplace=True)
        self.df = df
        return self.df

class DataLoader:
    def __init__(self, filepath):
        self.filepath = filepath
        self.df = None

    def load_data(self):
        self.df = pd.read_csv(self.filepath)
        return self.df

    def clean_data(self):
        df = self.df.copy()
        df['required_car_parking_space'].fillna(df['required_car_parking_space'].median(), inplace=True)
        df['required_car_parking_space'] = df['required_car_parking_space'].astype(int)
        df['avg_price_per_room'].fillna(df['avg_price_per_room'].median(), inplace=True)
        df['type_of_meal_plan'].fillna('Meal Plan 1', inplace=True)
        df.drop('Booking_ID', axis=1, inplace=True)
        self.df = df
        return self.df

"""The **`DataLoader`** class:

1. **Loads Data**: It reads data from a CSV file and stores it in a DataFrame.
2. **Cleans Data**: It fixes missing values in certain columns, removes unnecessary columns, and prepares the data for use.
"""

class Preprocessor:
    def __init__(self, df):
        self.df = df
        self.encoder = OneHotEncoder(sparse_output=False, handle_unknown='ignore')
        self.scaler = RobustScaler()
        self.label_encoder = LabelEncoder()
        self.nom_cols = ['type_of_meal_plan', 'room_type_reserved', 'market_segment_type']
        self.numerical_cols = ['no_of_adults', 'no_of_children', 'no_of_weekend_nights', 'no_of_week_nights',
                               'lead_time', 'avg_price_per_room', 'no_of_previous_cancellations',
                               'no_of_previous_bookings_not_canceled', 'no_of_special_requests']

    def handle_outliers(self):
        Q1 = self.df[self.numerical_cols].quantile(0.25)
        Q3 = self.df[self.numerical_cols].quantile(0.75)
        IQR = Q3 - Q1
        lower_bound = Q1 - 1.5 * IQR
        upper_bound = Q3 + 1.5 * IQR

        for col in self.numerical_cols:
            self.df[col] = np.where(self.df[col] < lower_bound[col], lower_bound[col], self.df[col])
            self.df[col] = np.where(self.df[col] > upper_bound[col], upper_bound[col], self.df[col])
        return self.df

    def split_data(self):
        X = self.df.drop('booking_status', axis=1)
        y = self.df['booking_status']
        return train_test_split(X, y, test_size=0.3, random_state=42)

    def encode_and_scale(self, x_train, x_test, y_train, y_test):
        self.encoder.fit(x_train[self.nom_cols])
        train_encoded = self.encoder.transform(x_train[self.nom_cols])
        test_encoded = self.encoder.transform(x_test[self.nom_cols])

        train_df = pd.DataFrame(train_encoded, columns=self.encoder.get_feature_names_out(self.nom_cols), index=x_train.index)
        test_df = pd.DataFrame(test_encoded, columns=self.encoder.get_feature_names_out(self.nom_cols), index=x_test.index)

        x_train = pd.concat([x_train.drop(self.nom_cols, axis=1), train_df], axis=1)
        x_test = pd.concat([x_test.drop(self.nom_cols, axis=1), test_df], axis=1)

        y_train = self.label_encoder.fit_transform(y_train)
        y_test = self.label_encoder.transform(y_test)

        x_train['arrival_year'] = self.label_encoder.fit_transform(x_train['arrival_year'])
        x_test['arrival_year'] = self.label_encoder.transform(x_test['arrival_year'])

        x_train = self.scaler.fit_transform(x_train)
        x_test = self.scaler.transform(x_test)

        return x_train, x_test, y_train, y_test

    def get_encoder_scaler(self):
        return self.encoder, self.label_encoder, self.scaler

"""The **`Preprocessor`** class is used to prepare the data for machine learning:

1. **Handling Outliers**: `handle_outliers` method identifies and adjusts any outliers in the numerical columns by using the Interquartile Range (IQR) method.

2. **Splitting Data**: `split_data` method separates the input features (`X`) from the target variable (`y`), and then splits the data into training and testing sets.

3. **Encoding and Scaling**: The `encode_and_scale` method:
   - One-hot encodes categorical variables (`type_of_meal_plan`, `room_type_reserved`, `market_segment_type`).
   - Label encodes the target variable (`booking_status`) and the `arrival_year` column.
   - Scales the numerical columns using a `RobustScaler` to handle potential outliers and scale the data.

In short, this class processes and prepares data by handling outliers, encoding categorical variables, scaling numerical data, and splitting the data into training and testing sets.
"""

class ModelTrainer:
    def __init__(self):
        self.model = RandomForestClassifier(random_state=42)

    def train(self, x_train, y_train):
        params = {
            'n_estimators': [100],
            'max_features': ['sqrt'],
            'min_samples_split': [3],
            'max_depth': [None]
        }
        grid = GridSearchCV(self.model, params, cv=5, scoring='accuracy')
        grid.fit(x_train, y_train)
        self.model = grid.best_estimator_
        print(f"Best Parameters: {grid.best_params_}")
        print(f"Best Cross-Validation Accuracy: {grid.best_score_:.4f}")
        return self.model

    def evaluate(self, x_test, y_test):
        y_pred = self.model.predict(x_test)
        y_proba = self.model.predict_proba(x_test)[:, 1]

        rf_acc = accuracy_score(y_test, y_pred)
        rf_f1 = f1_score(y_test, y_pred)
        rf_roc = roc_auc_score(y_test, y_proba)
        report = classification_report(y_test, y_pred)

        print(f"\nRandom Forest:")
        print(f"Accuracy = {rf_acc:.4f}")
        print(f"F1 Score = {rf_f1:.4f}")
        print(f"AUC = {rf_roc:.4f}")
        print("Classification Report:\n", report)

"""The **`ModelTrainer`** class is responsible for training and evaluating a machine learning model:

1. **Initialization (`__init__`)**:
   - It initializes the class with a **RandomForestClassifier** model, using a fixed random seed for reproducibility.

2. **Training (`train`)**:
   - The `train` method accepts training data (`x_train` and `y_train`).
   - It defines a set of hyperparameters (like `n_estimators`, `max_features`, etc.) for the Random Forest model.
   - It performs **GridSearchCV** to find the best hyperparameters by performing cross-validation (5-fold) and optimizing for accuracy.
   - After fitting the model, it updates the model to the best one found by the grid search.
   - The best hyperparameters and cross-validation accuracy are printed.

3. **Evaluation (`evaluate`)**:
   - The `evaluate` method accepts test data (`x_test` and `y_test`).
   - It predicts the labels for the test data and calculates the **probability** for the positive class.
   - It computes various evaluation metrics, such as **accuracy**, **F1 score**, and **AUC** (Area Under the ROC Curve).
   - The classification report, which shows precision, recall, and F1 score for each class, is printed.

This class allows you to train a **Random Forest** model using grid search for hyperparameter tuning, and then evaluate its performance using multiple metrics.

Below is the example if we do the HyperParameter tuning fully, with other options. But for now i'll just use the known parameter that before we have gain from the ML model
"""

# from sklearn.ensemble import RandomForestClassifier
# from sklearn.model_selection import GridSearchCV
# from sklearn.metrics import accuracy_score, f1_score, roc_auc_score, classification_report

# class ModelTrainer:
#     def __init__(self, random_state=42):
#         self.random_state = random_state
#         self.model = RandomForestClassifier(random_state=self.random_state)
#         self.best_models = {}

#     def train(self, x_train, y_train):
#         param_grid = {
#             "n_estimators": [50, 100, 200, 300],
#             "max_depth": [None, 5, 10, 20, 30],
#             "min_samples_split": [2, 3, 5, 10],
#             "max_features": ['sqrt', 'log2', None, 0.8]
#         }

#         grid = GridSearchCV(self.model, param_grid, cv=5, scoring='accuracy', n_jobs=-1, verbose=1)
#         grid.fit(x_train, y_train)

#         best_rf = grid.best_estimator_
#         self.best_models["Random Forest"] = best_rf

#         print(f"Best Parameters: {grid.best_params_}")
#         print(f"Best CV Accuracy: {grid.best_score_:.4f}")
#         return best_rf

#     def evaluate(self, x_test, y_test):
#         rf_model = self.best_models.get("Random Forest")
#         if rf_model is None:
#             raise ValueError("Model not trained yet. Call train() first.")

#         rf_pred = rf_model.predict(x_test)
#         rf_proba = rf_model.predict_proba(x_test)[:, 1]

#         rf_acc = accuracy_score(y_test, rf_pred)
#         rf_f1 = f1_score(y_test, rf_pred)
#         rf_roc = roc_auc_score(y_test, rf_proba)
#         report = classification_report(y_test, rf_pred, target_names=['Not_Canceled', 'Canceled'])

#         print("\nRandom Forest:")
#         print(f"Accuracy = {rf_acc:.4f}")
#         print(f"F1 Score = {rf_f1:.4f}")
#         print(f"AUC = {rf_roc:.4f}")
#         print("Classification Report:\n", report)

#         return rf_model

if __name__ == "__main__":
    loader = DataLoader("Dataset_B_hotel.csv")
    df = loader.load_data()
    df = loader.clean_data()

    # Initialize Preprocessor and preprocess data
    preprocessor = Preprocessor(df)

    # Handle outliers
    df = preprocessor.handle_outliers()

    # Split the data into train and test sets
    x_train, x_test, y_train, y_test = preprocessor.split_data()

    # Encode categorical features and scale numerical features
    x_train, x_test, y_train, y_test = preprocessor.encode_and_scale(x_train, x_test, y_train, y_test)

    # Get the encoder and scaler for saving or future use
    encoder, label_encoder, scaler = preprocessor.get_encoder_scaler()

    # Initialize ModelTrainer and train the model
    model_trainer = ModelTrainer()
    model = model_trainer.train(x_train, y_train)

    # Evaluate the model
    model_trainer.evaluate(x_test, y_test)

"""### Conclusion:

The **Random Forest** model, after tuning with **GridSearchCV**, performed well with the best hyperparameters being:
- `max_depth = None`
- `max_features = 'sqrt'`
- `min_samples_split = 3`
- `n_estimators = 100`

(P.S. gained from the previous ML training)

The model achieved a **cross-validation accuracy** of 89.35%. After training on the entire dataset, the model showed an **accuracy of 89.86%**, with an **F1 score** of 92.57% and an **AUC** of 95.45%.

The **classification report** indicates that:
- The model performed well in predicting **Not Canceled** bookings (class 1) with high **recall** (0.95) and **precision** (0.91).
- **Canceled** bookings (class 0) had a **recall** of 0.80, meaning the model missed some canceled bookings but performed well on the ones it predicted as canceled.

Overall, the model is reliable for predicting **Not Canceled** bookings with high precision and recall, but it could benefit from further tuning to improve performance on the **Canceled** class. The Random Forest model provides a solid foundation for this task and can be used for practical deployment, with room for improvement in predicting the canceled class.
"""

